# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fe64d59f8127f82a83e4ffced93a8786e037a8c009bb439724629fd731b4883d5d286c1d8b38db9ebf05572e54d2da4b37b95ad4fd295c5f33f72936628b5ae

test:
  secret_key_base: 95932a73d9e141d9a2b7533fc08644b11b7ae8e7335a43a4abb54374a04cb3f6cf3d7d1561c9158c453e6824c5be213b07fd6152b807cbb8bd3cc83cd8cb5cf9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 930542ff6be185dfda203b24c0b0d4525740850ac3e45d4565709e542d783395b798a9e5e7bd5c3e12d78b983a82b21a2e64aec2b690580f43f3ccaf27ea5781#<%= ENV["SECRET_KEY_BASE"] %>
